### ISSUE TITLE
Running GCN on RTFM Causes Circular Import

### ISSUE THREAD

**Issue by Spiph** [ZhengyaoJiang/GTG#2] opened 2021-08-18 13:31 UTC
Running GTG on RTFM  via `python -m torchbeast.monobeast --env rtfm --agent GCN --xpid rtfm-test` causes the following error:

```
ImportError: cannot import name 'BaseMonster' from partially initialized module 'environment.rtfm.dynamics.monster' (most likely due to a circular import) (/home/icannon/code/GTG/environment/rtfm/dynamics/monster/__init__.py)
```

Do you have any idea where this is coming from?

**Comment by ZhengyaoJiang** [comment] 2021-08-19 12:41
Thanks! This is probably caused by the refactoring before the repo become public. Now it should have been fixed with the latest commits.

**Closed as completed by ZhengyaoJiang** 2021-08-19 12:41 UTC

**Comment by Spiph** [comment] 2021-08-19 13:19
it looks like you removed the agent import from the monster package since that is what caused the circular import. While this does solve the circular import, there is another issue down the line in featurizer.py where it cannot get QueuedAgent from agent.py. 

```
module 'environment.rtfm.dynamics.monster' has no attribute 'QueuedAgent'
  File "/home/aicrowd/GTG/environment/rtfm/featurizer.py", line 182, in Symbol
    M.QueuedAgent,
```

Should agent.py be incorporated into another file/package? It looks like it does not need to be in monster since agent.py depends on BaseMonster which in turn depends on agent - causing the circular import.
